owner: korynbid # Your GitHub user or org name
repo: korynbid.github.io           # Name of this status repo

sites:
  - name: Project Arkanum
    url: https://debweb.marten-grue.ts.net

status-website:
  name: System Status
  introTitle: "Live Service Monitoring"
  baseUrl: /    # Omit if using a custom CNAME domain below
  # cname: status.yourdomain.com # Optional custom domain setup
